services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '6831:6831/udp'
      - '16686:16686'

  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    environment:
      GF_LOG_LEVEL: debug
      GF_LOG_FILTERS: plugins:debug
      GF_SERVER_ROOT_URL: http://admin:admin@grafana:3000
      JAEGER_AGENT_HOST: 'jaeger'
      RUST_LOG: grafana_plugin_sdk=debug,info

  frontend:
    image: node:24
    command:
      - sh
      - -c
      - 'corepack enable && yarn && yarn dev'
    working_dir: /home/node/app
    volumes:
      - '.:/home/node/app'

  backend:
    build: .
    volumes:
      - '/usr/local/cargo'
      - '/usr/src/backend/target'
      - './backend:/usr/src/backend'
      - '../hsds-client-rs:/usr/src/hsds-client-rs'
      - './dist:/usr/src/dist'
    command:
      - cargo
      - watch
      - --why
      - -x
      - build
      - -s
      - rm -rf /usr/src/dist/gpx_hsds-datasource_linux_amd64 && cp target/debug/grafana-hsds-datasource /usr/src/dist/gpx_hsds-datasource_linux_amd64 && nc -z grafana 10001
